### ISSUE TITLE
Khi người chơi làm sai liên tục thì thanh tiến trình chỉ được phép cập nhật một lần, và chỉ cập nhật khi trả lời đúng 1 lần duy nhất

### ISSUE THREAD

**Issue by tuanthanh-nguyen** [atonggiang/InfrontBehind_Dragonlearn.in#20]
Làm sai 1 lần thì lùi 1 tiến trình trong trường hợp lần đầu tiên làm sai, kể cả lần sau làm sai tiếp cũng không cập nhật
Làm đúng thì thêm tiến trình trong trường hợp lần đầu tiên làm đúng, nếu làm sai trước đó thì không cập nhật

**Comment by atonggiang** [comment]
Làm sai 1 lần thì lùi 1 tiến trình trong trường hợp lần đầu tiên làm sai, kể cả lần sau làm sai tiếp cũng không cập nhật
Làm đúng thì thêm tiến trình trong trường hợp lần đầu tiên làm đúng, nếu làm sai trước đó thì không cập nhật
